export type TaskStatus = 'pending' | 'in-progress' | 'complete' | 'cancelled';
export type ConfidenceLevel = 'low' | 'medium' | 'high';
export type GameMode = 'shooting' | 'wheel';
export type ReflectionOption =
  | 'overran'
  | 'distracted'
  | 'procrastinating'
  | 'custom';

export interface Task {
  id: string;
  userId: string;
  title: string;
  dueDate: string; // ISO date string
  estimatedMinutes: number;
  actualMinutes: number; // tracked by timer
  status: TaskStatus;
  requiresTaskIds: string[]; // predecessor task IDs
  isAutoGenerated: boolean; // true if created by study planner
  parentTestId?: string; // set if auto-generated for a test
  createdAt: string;
}

export interface Topic {
  id: string;
  name: string;
  notes: string;
  confidence: ConfidenceLevel;
  quizHistory: QuizAttempt[];
}

export interface Test {
  id: string;
  userId: string;
  name: string;
  testDate: string;
  topics: Topic[];
  revisionSchedule: ScheduledSession[];
  createdAt: string;
}

export interface ScheduledSession {
  id: string;
  topicId: string;
  scheduledDate: string;
  durationMinutes: number;
  reviewNumber: number; // 1st review, 2nd review, etc.
}

export interface QuizQuestion {
  question: string;
  options: string[];
  answer: string;
}

export interface QuizAttempt {
  date: string;
  score: number; // 0-100
  totalQuestions: number;
}

export interface DayReport {
  date: string;
  userId: string;
  completedTaskIds: string[];
  reflectionResponse: ReflectionEntry | null;
  gameMode: GameMode;
}

export interface ReflectionEntry {
  option: ReflectionOption;
  freeText?: string;
  reEstimateRequested?: boolean;
}
