import { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useGameStore } from '../store/useGameStore';
import { useTaskStore } from '../store/useTaskStore';
import { useTestStore } from '../store/useTestStore';
import { useTimerStore } from '../store/useTimerStore';
import { useQuizStore } from '../store/useQuizStore';
import { PixelButton } from '../components/shared/PixelButton';
import { TaskCard } from '../components/tasks/TaskCard';
import { TimerModal } from '../components/game/TimerModal';
import { Modal } from '../components/shared/Modal';
import { quizGenerate, patchTaskUnderstanding } from '../api';
import type { Topic } from '../types';
import shotBg from '../../assets/backgrounds/hit_me_with_a_shotbg.png';

/** Find a topic matching the task's title from tests (first match). */
function findTopicForTask(taskTitle: string, tests: { id: string; topics?: { id: string; name: string; summaryPdf?: { name: string; dataUrl: string } }[] }[]): { topic: Topic; testId: string } | null {
  for (const test of tests) {
    for (const topic of test.topics ?? []) {
      if (topic.name === taskTitle) return { topic: topic as Topic, testId: test.id };
    }
  }
  return null;
}

export function GameShootingPage() {
  const navigate = useNavigate();
  const taskQueue = useGameStore((s) => s.taskQueue);
  const getTaskById = useTaskStore((s) => s.getTaskById);
  const markComplete = useTaskStore((s) => s.markComplete);
  const tests = useTestStore((s) => s.tests);
  const setQuiz = useQuizStore((s) => s.setQuiz);
  const [selectedTaskId, setSelectedTaskId] = useState<string | null>(null);
  const [timerModalOpen, setTimerModalOpen] = useState(false);
  const [showCompleteModal, setShowCompleteModal] = useState(false);
  const [completeModalStep, setCompleteModalStep] = useState<'choice' | 'rating' | 'quizLoading' | 'quizError'>('choice');
  const [quizGenerating, setQuizGenerating] = useState(false);
  const [understandingRating, setUnderstandingRating] = useState(0);
  const quizPdfInputRef = useRef<HTMLInputElement>(null);
  const [understandingSubmitting, setUnderstandingSubmitting] = useState(false);

  const tasks = taskQueue
    .map((id) => getTaskById(id))
    .filter((t): t is NonNullable<typeof t> => t != null);
  const incompleteTasks = tasks.filter((t) => t.status !== 'complete');

  const selectedTask = selectedTaskId ? getTaskById(selectedTaskId) : null;
  const topicForTask = selectedTask ? findTopicForTask(selectedTask.title, tests) : null;

  const handleConfirmTask = () => {
    if (!selectedTask) return;
    useTimerStore.getState().startTimer(selectedTask.id, selectedTask.estimatedMinutes);
    setTimerModalOpen(true);
  };

  const handleTimerComplete = () => {
    if (selectedTaskId) markComplete(selectedTaskId);
    setSelectedTaskId(null);
    setTimerModalOpen(false);
  };

  const handleCompleteClick = () => {
    if (!selectedTask?.isAutoGenerated) {
      handleTimerComplete();
      return;
    }
    setCompleteModalStep('choice');
    setShowCompleteModal(true);
  };

  const closeCompleteModal = () => {
    setShowCompleteModal(false);
    setCompleteModalStep('choice');
    setQuizGenerating(false);
    setUnderstandingRating(0);
    setUnderstandingSubmitting(false);
    if (quizPdfInputRef.current) quizPdfInputRef.current.value = '';
  };

  const handleTakeQuizClick = () => {
    quizPdfInputRef.current?.click();
  };

  const handleQuizPdfSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file || !file.name.toLowerCase().endsWith('.pdf')) return;
    setCompleteModalStep('quizLoading');
    setQuizGenerating(true);
    try {
      const questions = await quizGenerate(file);
      setQuizGenerating(false);
      const topicName = file.name.replace(/\.pdf$/i, '');
      closeCompleteModal();
      setQuiz(questions, topicName);
      navigate('/quiz');
    } catch {
      setQuizGenerating(false);
      setCompleteModalStep('quizError');
    }
  };

  const handleRateUnderstanding = () => {
    setUnderstandingRating(0);
    setCompleteModalStep('rating');
  };

  const handleRatingConfirm = async () => {
    if (understandingRating < 1 || understandingRating > 5 || !selectedTaskId) return;
    const taskIdForPatch = topicForTask?.topic.id ?? selectedTaskId;
    setUnderstandingSubmitting(true);
    try {
      await patchTaskUnderstanding(taskIdForPatch, understandingRating);
      closeCompleteModal();
    } catch {
      closeCompleteModal();
    } finally {
      setUnderstandingSubmitting(false);
    }
  };

  return (
    <div
      className="font-body w-full min-h-screen flex flex-col"
      style={{
        backgroundImage: `url(${shotBg})`,
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        position: 'relative',
      }}
    >
      <div className="flex-1 flex flex-col w-full">
      {!timerModalOpen && (
      <>
      <div className="flex items-center justify-between flex-wrap gap-4 p-4">
        <h2 className="font-pixel text-sm text-[var(--color-cream)]">
          Hit me with your best shot
        </h2>
        <PixelButton
          label="Back to home"
          variant="ghost"
          onClick={() => navigate('/')}
          className="!bg-[#D4A017] border-2 border-[var(--color-dark-brown)] !text-[var(--color-dark-brown)] font-bold"
        />
      </div>

      {/* Right wooden wall area: wanted posters and controls */}
      <div
        className="flex-1 flex flex-col items-center justify-center min-h-0 w-1/2 ml-auto pr-6 pl-4 py-6"
        style={{ minWidth: '50%' }}
      >
        <p className="text-[var(--color-cream)] text-sm text-center mb-6">
          Click a wanted poster to choose your task. Confirm to start the timer. When you&apos;re done, we&apos;ll shoot it!
        </p>
        <div className="grid grid-cols-2 gap-4 mb-6 w-full max-w-md">
          {tasks.map((task) => (
            <TaskCard
              key={task.id}
              task={task}
              variant="wanted-poster"
              completed={task.status === 'complete'}
              selected={selectedTaskId === task.id}
              onClick={() => setSelectedTaskId(task.id)}
            />
          ))}
        </div>
        {incompleteTasks.length === 0 && (
          <p className="text-[var(--color-cream)] mb-4">All tasks done! Great job.</p>
        )}
        {selectedTask && selectedTask.status !== 'complete' && (
          <div
            className="rounded-lg border-2 p-4 w-full max-w-md"
            style={{
              backgroundColor: '#F5E6C8',
              borderColor: 'var(--color-dark-brown)',
            }}
          >
            <p className="font-body text-sm font-semibold text-[var(--color-dark-brown)] mb-3">
              Selected: {selectedTask.title}
            </p>
            <p className="text-xs text-[var(--color-dark-brown)] mb-4">
              {selectedTask.estimatedMinutes} min
            </p>
            <div className="flex items-center gap-4 flex-wrap justify-center">
              <PixelButton
                label="Confirm — start timer"
                variant="primary"
                onClick={handleConfirmTask}
                className="!bg-[#D4A017] border-4 border-[var(--color-dark-brown)] !text-[var(--color-dark-brown)] font-bold"
              />
              <PixelButton
                label="Cancel"
                variant="ghost"
                onClick={() => setSelectedTaskId(null)}
                className="!bg-[#C9B896] border-2 border-[var(--color-dark-brown)] !text-[var(--color-dark-brown)] font-bold hover:!brightness-95"
              />
            </div>
          </div>
        )}
      </div>
      </>
      )}

      <TimerModal
        isOpen={timerModalOpen}
        onClose={() => {
          setTimerModalOpen(false);
          setSelectedTaskId(null);
        }}
        taskTitle={selectedTask?.title ?? 'Task'}
        onComplete={handleCompleteClick}
        embedOnBackground
      />

      <Modal
        isOpen={showCompleteModal}
        onClose={closeCompleteModal}
        title={completeModalStep === 'rating' ? 'How well did you understand this topic?' : 'Complete'}
      >
        <div className="flex flex-col gap-4">
          {completeModalStep === 'choice' && (
            <>
              <input
                ref={quizPdfInputRef}
                type="file"
                accept=".pdf,application/pdf"
                className="hidden"
                onChange={handleQuizPdfSelect}
                aria-hidden
              />
              <div className="flex gap-3 justify-end">
                <PixelButton
                  label="Take a Quiz"
                  variant="primary"
                  onClick={handleTakeQuizClick}
                  disabled={quizGenerating}
                />
                <PixelButton label="Rate Your Understanding" variant="secondary" onClick={handleRateUnderstanding} />
              </div>
            </>
          )}
          {completeModalStep === 'quizLoading' && (
            <p className="text-sm text-[var(--color-brown)]">Generating quiz...</p>
          )}
          {completeModalStep === 'quizError' && (
            <>
              <p className="text-sm text-[var(--color-casino-red)]">
                Failed to generate quiz. Please try again.
              </p>
              <div className="flex justify-end">
                <PixelButton label="Back" variant="secondary" onClick={() => setCompleteModalStep('choice')} />
              </div>
            </>
          )}
          {completeModalStep === 'rating' && (
            <>
              <p className="text-sm text-[var(--color-brown)]">
                Rate your understanding from 1 (struggled) to 5 (very well).
              </p>
              <div className="flex gap-2 justify-center" role="group" aria-label="Rating 1 to 5 stars">
                {[1, 2, 3, 4, 5].map((star) => (
                  <button
                    key={star}
                    type="button"
                    onClick={() => setUnderstandingRating(star)}
                    className={`w-10 h-10 rounded border-2 font-pixel text-sm focus-visible:outline focus-visible:outline-2 ${
                      understandingRating >= star
                        ? 'border-[var(--color-brown)] bg-[var(--color-gold)] text-[var(--color-dark-brown)]'
                        : 'border-[var(--color-brown)] bg-[var(--color-cream)] text-[var(--color-brown)] hover:bg-[var(--color-beige)]'
                    }`}
                    aria-label={`${star} star${star === 1 ? '' : 's'}`}
                    aria-pressed={understandingRating >= star}
                  >
                    ★
                  </button>
                ))}
              </div>
              <div className="flex justify-end">
                <PixelButton
                  label="Confirm"
                  variant="primary"
                  onClick={handleRatingConfirm}
                  disabled={understandingRating < 1 || understandingRating > 5 || understandingSubmitting}
                />
              </div>
            </>
          )}
        </div>
      </Modal>
      </div>
    </div>
  );
}
