import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useGameStore } from '../store/useGameStore';
import { useTaskStore } from '../store/useTaskStore';
import type { GameMode, Task } from '../types';
import { PixelButton } from '../components/shared/PixelButton';
import { Modal } from '../components/shared/Modal';
import cat1 from '../../assets/elements/cat_1.png';
import cat2 from '../../assets/elements/cat_2.png';

export function GameChoicePage() {
  const navigate = useNavigate();
  const setGameMode = useGameStore((s) => s.setGameMode);
  const setTaskQueue = useGameStore((s) => s.setTaskQueue);
  const setFunTask = useGameStore((s) => s.setFunTask);
  const getTodaysTasks = useTaskStore((s) => s.getTodaysTasks);
  const addTask = useTaskStore((s) => s.addTask);

  const [funTaskModalOpen, setFunTaskModalOpen] = useState(false);
  const [funTaskTitle, setFunTaskTitle] = useState('Watch an episode on Netflix');

  const todayISO = () => new Date().toISOString().slice(0, 10);

  const goToGame = (mode: GameMode) => {
    const todaysTasks = getTodaysTasks();
    const taskIds = todaysTasks.map((t) => t.id);
    setGameMode(mode);
    setTaskQueue(taskIds);
    navigate(mode === 'shooting' ? '/game/shooting' : '/game/wheel');
  };

  const handleConfirmWheel = () => {
    const baseTitle = funTaskTitle.trim() || 'Fun break';
    const funTask: Task = {
      id: crypto.randomUUID(),
      userId: 'local',
      title: baseTitle,
      dueDate: todayISO(),
      estimatedMinutes: 30,
      actualMinutes: 0,
      status: 'pending',
      requiresTaskIds: [],
      isAutoGenerated: true,
      parentTestId: undefined,
      createdAt: new Date().toISOString(),
      completedAt: null,
    };
    addTask(funTask);
    setFunTask(funTask.id);

    const todaysTasks = getTodaysTasks();
    const taskIds = todaysTasks.map((t) => t.id);
    setGameMode('wheel');
    setTaskQueue(taskIds);
    setFunTaskModalOpen(false);
    navigate('/game/wheel');
  };

  return (
    <div className="font-body p-6 max-w-2xl mx-auto text-center">
      <h2 className="font-pixel text-sm text-[var(--color-dark-brown)] mb-6">
        Select today&apos;s game
      </h2>

      <div className="grid gap-6 sm:grid-cols-2">
        <button
          type="button"
          onClick={() => goToGame('shooting')}
          className="flex flex-col items-center gap-4 p-6 rounded-lg border-4 border-[var(--color-saloon-wood)] bg-[var(--color-saloon-tan)] hover:brightness-105 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--color-gold)]"
          aria-label="Play shooting game: Hit me with your best shot"
        >
          <img src={cat1} alt="" width={80} height={80} className="object-contain" />
          <span className="font-pixel text-xs text-[var(--color-dark-brown)]">
            Hit me with your best shot
          </span>
          <p className="font-body text-sm text-[var(--color-brown)]">
            Shoot your tasks down one by one in whatever order you like.
          </p>
        </button>

        <button
          type="button"
          onClick={() => setFunTaskModalOpen(true)}
          className="flex flex-col items-center gap-4 p-6 rounded-lg border-4 border-[var(--color-casino-dark)] bg-[var(--color-beige)] hover:brightness-105 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--color-gold)]"
          aria-label="Play wheel game: You spin me right round"
        >
          <img src={cat2} alt="" width={80} height={80} className="object-contain" />
          <span className="font-pixel text-xs text-[var(--color-dark-brown)]">
            You spin me right round
          </span>
          <p className="font-body text-sm text-[var(--color-brown)]">
            Feeling lucky? Let fate decide the order of your tasks today.
          </p>
        </button>
      </div>

      <div className="mt-8">
        <PixelButton
          label="Back to week plan"
          variant="ghost"
          onClick={() => navigate('/')}
        />
      </div>

      <Modal
        isOpen={funTaskModalOpen}
        onClose={() => setFunTaskModalOpen(false)}
        title="Add a fun task"
      >
        <div className="space-y-4">
          <p className="text-[var(--color-brown)] text-sm">
            Before we spin the wheel, think of a fun break task for today (e.g. &quot;watch Netflix&quot; or &quot;take a nap&quot;). If it isn&apos;t completed by the end of the day, it won&apos;t be saved.
          </p>
          <div>
            <label className="block font-body text-sm text-[var(--color-dark-brown)] mb-1">
              Fun task name
            </label>
            <input
              type="text"
              value={funTaskTitle}
              onChange={(e) => setFunTaskTitle(e.target.value)}
              className="w-full px-3 py-2 border-2 border-[var(--color-brown)] rounded bg-[var(--color-warm-white)] font-body"
              placeholder="e.g. Watch Netflix"
            />
          </div>
          <div className="flex justify-end gap-2">
            <PixelButton
              label="Cancel"
              variant="ghost"
              onClick={() => setFunTaskModalOpen(false)}
            />
            <PixelButton
              label="Start game"
              variant="primary"
              onClick={handleConfirmWheel}
            />
          </div>
        </div>
      </Modal>
    </div>
  );
}
