import { useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTaskStore } from '../store/useTaskStore';
import { LOCAL_USER_ID } from '../store/useUserStore';
import type { Task } from '../types';
import { PixelButton } from '../components/shared/PixelButton';
import { Modal } from '../components/shared/Modal';
import { TaskCard } from '../components/tasks/TaskCard';

function formatDayLabel(dateStr: string): string {
  const today = new Date().toISOString().slice(0, 10);
  if (dateStr === today) return 'Today';
  const d = new Date(dateStr + 'T12:00:00');
  return d.toLocaleDateString('en-GB', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
  });
}

function getWeekDates(): string[] {
  const dates: string[] = [];
  const start = new Date();
  for (let i = 0; i < 8; i++) {
    const d = new Date(start);
    d.setDate(d.getDate() + i);
    dates.push(d.toISOString().slice(0, 10));
  }
  return dates;
}

export function WeekPlanPage() {
  const navigate = useNavigate();
  const tasks = useTaskStore((s) => s.tasks);
  const moveTaskToDate = useTaskStore((s) => s.moveTaskToDate);
  const addTask = useTaskStore((s) => s.addTask);

  const weekData = useMemo(() => {
    const activeTasks = tasks.filter((t) => t.status !== 'cancelled');
    return getWeekDates().map((date) => {
      const dayTasks = activeTasks.filter((t) => t.dueDate === date);
      const totalMinutes = dayTasks.reduce((s, t) => s + t.estimatedMinutes, 0);
      return { date, tasks: dayTasks, totalMinutes };
    });
  }, [tasks]);

  const [addModalOpen, setAddModalOpen] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newMinutes, setNewMinutes] = useState(30);
  const [newDueDate, setNewDueDate] = useState(() =>
    new Date().toISOString().slice(0, 10)
  );
  const [draggedId, setDraggedId] = useState<string | null>(null);

  const handleDragStart = (_e: React.DragEvent, taskId: string) => {
    setDraggedId(taskId);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
  };

  const handleDrop = (e: React.DragEvent, date: string) => {
    e.preventDefault();
    const taskId = e.dataTransfer.getData('text/plain');
    if (taskId) moveTaskToDate(taskId, date);
    setDraggedId(null);
  };

  const handleAddTask = () => {
    if (!newTitle.trim()) return;
    const task: Task = {
      id: crypto.randomUUID(),
      userId: LOCAL_USER_ID,
      title: newTitle.trim(),
      dueDate: newDueDate,
      estimatedMinutes: newMinutes,
      actualMinutes: 0,
      status: 'pending',
      requiresTaskIds: [],
      isAutoGenerated: false,
      createdAt: new Date().toISOString(),
    };
    addTask(task);
    setNewTitle('');
    setNewMinutes(30);
    setNewDueDate(new Date().toISOString().slice(0, 10));
    setAddModalOpen(false);
  };

  return (
    <div className="font-body p-4 max-w-6xl mx-auto">
      <h2 className="font-pixel text-sm text-[var(--color-dark-brown)] mb-4">
        Your tasks — this week
      </h2>
      <p className="text-[var(--color-brown)] text-sm mb-4">
        Drag tasks between days. Total estimated time is shown under each day.
      </p>

      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8 gap-4 mb-6">
        {weekData.map(({ date, tasks, totalMinutes }) => (
          <div
            key={date}
            onDragOver={handleDragOver}
            onDrop={(e) => handleDrop(e, date)}
            className={`min-h-[180px] rounded-lg border-2 border-dashed p-3 transition-colors ${
              draggedId
                ? 'border-[var(--color-gold)] bg-[var(--color-beige)]/50'
                : 'border-[var(--color-brown)] bg-[var(--color-cream)]'
            }`}
          >
            <div className="font-pixel text-[10px] text-[var(--color-dark-brown)] mb-2">
              {formatDayLabel(date)}
            </div>
            <div className="space-y-2">
              {tasks.map((task) => (
                <TaskCard
                  key={task.id}
                  task={task}
                  variant="list"
                  draggable
                  onDragStart={handleDragStart}
                />
              ))}
            </div>
            <div className="mt-2 pt-2 border-t border-[var(--color-brown)] font-body text-xs text-[var(--color-brown)]">
              Total: {totalMinutes} min
            </div>
          </div>
        ))}
      </div>

      <div className="flex flex-wrap gap-4">
        <PixelButton
          label="Add task"
          variant="primary"
          onClick={() => setAddModalOpen(true)}
        />
        <PixelButton
          label="Confirm"
          variant="primary"
          onClick={() => navigate('/game-choice')}
        />
      </div>

      <Modal
        isOpen={addModalOpen}
        onClose={() => setAddModalOpen(false)}
        title="Add task"
      >
        <div className="space-y-4">
          <div>
            <label className="block font-body text-sm text-[var(--color-dark-brown)] mb-1">
              Task name
            </label>
            <input
              type="text"
              value={newTitle}
              onChange={(e) => setNewTitle(e.target.value)}
              className="w-full px-3 py-2 border-2 border-[var(--color-brown)] rounded bg-[var(--color-warm-white)] font-body"
              placeholder="e.g. Maths revision"
            />
          </div>
          <div>
            <label className="block font-body text-sm text-[var(--color-dark-brown)] mb-1">
              Estimated minutes
            </label>
            <input
              type="number"
              min={1}
              value={newMinutes}
              onChange={(e) => setNewMinutes(Number(e.target.value) || 30)}
              className="w-full px-3 py-2 border-2 border-[var(--color-brown)] rounded bg-[var(--color-warm-white)] font-body"
            />
          </div>
          <div>
            <label className="block font-body text-sm text-[var(--color-dark-brown)] mb-1">
              Due date
            </label>
            <input
              type="date"
              value={newDueDate}
              onChange={(e) => setNewDueDate(e.target.value)}
              className="w-full px-3 py-2 border-2 border-[var(--color-brown)] rounded bg-[var(--color-warm-white)] font-body"
            />
          </div>
          <PixelButton
            label="Add task"
            variant="primary"
            onClick={handleAddTask}
            disabled={!newTitle.trim()}
          />
        </div>
      </Modal>
    </div>
  );
}
